"""Added users table

Revision ID: 1e0e8b820f3b
Revises: None
Create Date: 2014-06-12 21:17:31.254604

"""

# revision identifiers, used by Alembic.
revision = '1e0e8b820f3b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
