"""Add is_active and email to User

Revision ID: 27843c30fa8b
Revises: 2aa3841671ce
Create Date: 2014-06-14 00:37:34.414716

"""

# revision identifiers, used by Alembic.
revision = '27843c30fa8b'
down_revision = '2aa3841671ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    ### end Alembic commands ###
