"""Extend users table

Revision ID: 2aa3841671ce
Revises: 1e0e8b820f3b
Create Date: 2014-06-13 22:05:59.802991

"""

# revision identifiers, used by Alembic.
revision = '2aa3841671ce'
down_revision = '1e0e8b820f3b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users')
    op.drop_column('users', 'username')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'avatar')
    ### end Alembic commands ###
