"""fix is_active in User

Revision ID: 2e7ec0792ccd
Revises: 27843c30fa8b
Create Date: 2014-06-14 00:43:07.457143

"""

# revision identifiers, used by Alembic.
revision = '2e7ec0792ccd'
down_revision = '27843c30fa8b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    ### end Alembic commands ###
