"""Extend Task model with description and uuid fields

Revision ID: 4da3f1f3d053
Revises: 235612c48678
Create Date: 2014-07-28 18:39:10.804196

"""

# revision identifiers, used by Alembic.
revision = '4da3f1f3d053'
down_revision = '235612c48678'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('title', sa.String(length=200), nullable=True))
    op.add_column('tasks', sa.Column('uuid', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'uuid')
    op.drop_column('tasks', 'title')
    op.drop_column('tasks', 'description')
    ### end Alembic commands ###
