"""Add password field to User model

Revision ID: b822c4f1549
Revises: 2e7ec0792ccd
Create Date: 2014-06-21 00:18:17.406834

"""

# revision identifiers, used by Alembic.
revision = 'b822c4f1549'
down_revision = '2e7ec0792ccd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    ### end Alembic commands ###
